query MyQuery {
    listTodos {
        items {
            id
            content
            isDone
            tags {
                items {
                    tag {
                        name
                    }
                }
            }
        }
    }
}